### ISSUE TITLE
import issue with brazil_soybeans.ipynb

### ISSUE THREAD

**Issue by sahuguet** [gro-intelligence/api-client#290]
The import needs to be changed to
`from groclient.crop_model import CropModel`.

https://github.com/gro-intelligence/api-client/blob/development/api/client/samples/crop_models/brazil_soybeans.ipynb

**Comment by nemozen** [comment]
FYI I reran the notebook as is with the  latest version of the client and the backward compatibility shim https://github.com/gro-intelligence/api-client/blob/development/api/client/crop_model/__init__.py  is behaving as expected, i..e logs a warning but the code works.

**Comment by jli** [comment]
The import was updated in #296.
